CREATE TABLE STUDENT (
    Student_ID INT PRIMARY KEY,
    Student_Name VARCHAR(255) NOT NULL,
    Student_Degree VARCHAR(50) NOT NULL,
    Student_Major VARCHAR(100) NOT NULL
);

CREATE TABLE SUBJECT (
    Subject_ID VARCHAR(30) PRIMARY KEY,
    Subject_Name VARCHAR(255) NOT NULL,
    Subject_Major VARCHAR(100) NOT NULL
);

CREATE TABLE STUDENT_HAS_SUBJECT (
    SUBJECT_Subject_ID INT,
    STUDENT_Student_ID INT,
    PRIMARY KEY (SUBJECT_Subject_ID, STUDENT_Student_ID),
    FOREIGN KEY (SUBJECT_Subject_ID) REFERENCES SUBJECT(Subject_ID),
    FOREIGN KEY (STUDENT_Student_ID) REFERENCES STUDENT(Student_ID)
);

CREATE TABLE SCHEDULE (
    SUBJECT_Subject_ID INT,
    Day VARCHAR(10) NOT NULL,
    Start_Time INT NOT NULL,
    End_Time INT NOT NULL,
    FOREIGN KEY (SUBJECT_Subject_ID) REFERENCES SUBJECT(Subject_ID)
);

CREATE TABLE ASSIGNMENT (
    Assignment_ID INT PRIMARY KEY,
    Assignment_Name VARCHAR(255) NOT NULL,
    Assignment_DueDate DATE NOT NULL,
		Assignment_DueTime Time NOT NULL,
    SUBJECT_Subject_ID INT,
    FOREIGN KEY (SUBJECT_Subject_ID) REFERENCES SUBJECT(Subject_ID)
);